### ISSUE TITLE
Modify XML schema for transaction and control

### ISSUE THREAD

**Issue by josecaster** [xlate/staedi#44]
Hi,

I am setting up a codeco 96b validation and I noticed you had some predefined files in the library. So I copied your EDIFACT/v3.xml and tried adding a single validation on segment DAM 9500(Type of Damage).

However, I get the message UNEXPECTED_SEGMENT which is pointing me to the DAM segment. I know it has something to do with the grouping of the DAM segment in the interchange XML element, but I just can't find the right way to do it.

Can you please assist?

[View codeco 95b:Truugo](https://www.truugo.com/edifact/d95b/codeco/) (DAM is under GRP5>GRP6>C821>7500(Type Of Damage))

My xml is as follows:
[codeco95b.zip](https://github.com/xlate/staedi/files/4809224/codeco95b.zip)

**Comment by MikeEdgar** [comment]
Hi @josecaster ,
The predefined schemas in the library are specifically used only for the control structures (UNB>UNG>UNH or UNB>UNH). As you are processing the input data, your application must set the *transaction* schema when it encounters the UNH segment (reader.setTransactionSchema). The reason for this design is that an application may not know the correct message schema to use until reading up to the UNH segment.

Instead of a schema file with `interchange`, you will want to create your XML with a `transaction` element only (plus all of the types you need). There is an example CONTRL schema in the test folder that might help: https://github.com/xlate/staedi/blob/master/src/test/resources/EDIFACT/CONTRL-v4r02.xml. Your transaction schema should not contain the UNH/UNT segments, as they are already handled by the predefined control schema.

Please note that if the DAM segment is nested in GRP5>GRP6, you will continue to receive unexpected segment errors unless you define all of preceding segments. Based on the schema you linked on the Truugo site, your high level schema will be something like this (note that UNH and UNT are not mentioned):
```xml
<schema xmlns="http://xlate.io/EDISchema/v3">
  <transaction>
    <sequence>
      <segment type="BGM" minOccurs="1" maxOccurs="1" />
      <segment type="FTX" maxOccurs="9" />
      <segment type="RFF" maxOccurs="9" />
      <loop code="GRP1" minOccurs="0" maxOccurs="1">
        <sequence>
          <!-- omitted -->
        </sequence>
      </loop>
      <loop code="GRP2" minOccurs="1" maxOccurs="9">
        <sequence>
          <!-- omitted -->
        </sequence>
      </loop>
      <loop code="GRP3" minOccurs="0" maxOccurs="999">
        <sequence>
          <!-- omitted -->
        </sequence>
      </loop>
      <loop code="GRP5" minOccurs="1" maxOccurs="999">
        <sequence>
          <segment type="EQD" minOccurs="1" maxOccurs="1" />
          <!-- omitted RFF through EQA -->
          <loop code="GRP6" minOccurs="1" maxOccurs="999">
            <segment type="DAM" minOccurs="1" maxOccurs="1" />
          </loop>
          <!-- omitted GRP7 and NAD -->
        </sequence>
      </loop>
      <segment type="CNT" minOccurs="1" maxOccurs="1" />
    </sequence>
  </transaction>
  <!-- elementType, compositeType, and segmentType for the items in the transaction -->
</schema>
```

**Comment by josecaster** [comment]
Thanks Mike,

Once again. my question has been answered.
I get it now.
